version: 2
jobs:
  build:
    working_directory: ~/image
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/image.tar
      - run:
          name: Lint Dockerfile
          command: |
            docker run --rm -i hadolint/hadolint < ./Dockerfile
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/image.tar | true
      - run:
          name: Build Docker image
          command: |
            docker build --cache-from=image -t centos-rails .
      - run:
          name: Test Docker image
          command: |
            wget https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
            chmod +x ./container-structure-test-linux-amd64 
            mv ./container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
            container-structure-test test --image centos-rails --config ./container-structure-test.yml
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/image.tar centos-rails
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/image.tar
      - run:
          name: rails new Project
          command: |
            docker run -it --rm centos-rails bash -c "gem install rails && cd /tmp && rails new test-app -d mysql"
      - run:
          name: Show docker image size
          command: |
            docker images
            ls -l /caches/image.tar
      - run:
          name: Show versions
          command: |
            docker run -it --rm centos-rails bash -c "ruby -v"
            docker run -it --rm centos-rails bash -c "gem -v"
            docker run -it --rm centos-rails bash -c "bundle -v"

workflows:
  version: 2

  build:
    jobs:
      - build
